-- File inventory table for duplicate detection and storage auditing.
-- Generated by scan_drive_md5.ps1 and imported via COPY.
--
-- Import CSV:
--   \COPY file_inventory FROM 'scan.csv' WITH (FORMAT CSV, HEADER TRUE, ENCODING 'UTF8');
--
-- Multiple drives can be imported into the same table — use scan_label to
-- distinguish them and query across drives for cross-drive duplicates.

DROP TABLE IF EXISTS file_inventory;

CREATE TABLE file_inventory (
    id               BIGSERIAL    PRIMARY KEY,

    -- Scan metadata
    scan_label       TEXT         NOT NULL,             -- e.g. "Seagate 4TB", "F:"
    scanned_at       TIMESTAMP    NOT NULL,             -- when the scan ran

    -- File location
    full_path        TEXT         NOT NULL,             -- absolute path on source machine
    file_name        TEXT         NOT NULL,             -- filename + extension only
    file_extension   TEXT,                              -- lower-cased, e.g. ".jpg"
    parent_directory TEXT,                              -- folder containing the file
    drive_or_volume  TEXT,                              -- e.g. "F:", "\\NAS"

    -- File content identity
    file_size_bytes  BIGINT       NOT NULL,
    md5_hash         CHAR(32)     NOT NULL,             -- lower-cased hex MD5

    -- File timestamps (local time from source machine)
    file_created_at  TIMESTAMP,
    file_modified_at TIMESTAMP,

    -- File flags
    is_hidden        BOOLEAN,
    is_readonly      BOOLEAN
);

-- Duplicate detection: primary index — same content must have same hash AND size
CREATE INDEX idx_fi_hash_size   ON file_inventory (md5_hash, file_size_bytes);

-- Hash-only lookups (e.g. "does this file exist anywhere?")
CREATE INDEX idx_fi_hash        ON file_inventory (md5_hash);

-- Path lookups (equality / ORDER BY)
CREATE INDEX idx_fi_full_path         ON file_inventory (full_path);

-- Case-insensitive prefix matching (ILIKE 'prefix%').
-- A plain B-tree index cannot satisfy ILIKE; this functional index on lower()
-- with text_pattern_ops allows queries of the form:
--   WHERE lower(full_path) LIKE 'f:\sortoutall%'
CREATE INDEX idx_fi_full_path_lower   ON file_inventory (lower(full_path) text_pattern_ops);

-- Extension filtering (e.g. "show me all .mp4 duplicates")
CREATE INDEX idx_fi_extension   ON file_inventory (file_extension);

-- Per-drive/scan queries
CREATE INDEX idx_fi_scan_label  ON file_inventory (scan_label);

-- -----------------------------------------------------------------------
-- USEFUL QUERIES
-- -----------------------------------------------------------------------

-- 1. All duplicate sets (files with identical content, regardless of name/path).
--    Both hash AND size must match — a hash alone is not sufficient evidence.
--
-- SELECT
--     md5_hash,
--     file_size_bytes,
--     COUNT(*)          AS copy_count,
--     SUM(file_size_bytes) - file_size_bytes AS wasted_bytes,
--     ARRAY_AGG(full_path ORDER BY scan_label, full_path) AS paths
-- FROM file_inventory
-- GROUP BY md5_hash, file_size_bytes
-- HAVING COUNT(*) > 1
-- ORDER BY wasted_bytes DESC;


-- 2. Duplicates that exist on at least two different drives/volumes
--    (safe to delete the copy on the drive you're cleaning up).
--
-- SELECT
--     md5_hash,
--     file_size_bytes,
--     ARRAY_AGG(DISTINCT drive_or_volume) AS on_drives,
--     ARRAY_AGG(full_path ORDER BY scan_label, full_path) AS all_paths
-- FROM file_inventory
-- GROUP BY md5_hash, file_size_bytes
-- HAVING COUNT(DISTINCT drive_or_volume) > 1
-- ORDER BY file_size_bytes DESC;


-- 3. For a specific drive, show files that have a copy on another drive
--    (i.e. safe to delete from this drive).
--
-- SELECT f.full_path, f.file_size_bytes, f.md5_hash
-- FROM file_inventory f
-- WHERE f.drive_or_volume = 'F:'
--   AND EXISTS (
--       SELECT 1 FROM file_inventory other
--       WHERE other.md5_hash        = f.md5_hash
--         AND other.file_size_bytes = f.file_size_bytes
--         AND other.drive_or_volume <> 'F:'
--   )
-- ORDER BY f.file_size_bytes DESC;


-- 4. Files that exist ONLY on one drive (not backed up elsewhere — do NOT delete).
--
-- SELECT f.full_path, f.file_size_bytes, f.md5_hash
-- FROM file_inventory f
-- GROUP BY f.md5_hash, f.file_size_bytes, f.full_path
-- HAVING COUNT(DISTINCT drive_or_volume) = 1
--    AND SUM(COUNT(*)) OVER (PARTITION BY f.md5_hash, f.file_size_bytes) = 1;


-- 5. Storage summary per drive and file type.
--
-- SELECT
--     drive_or_volume,
--     file_extension,
--     COUNT(*)                            AS file_count,
--     SUM(file_size_bytes)                AS total_bytes,
--     pg_size_pretty(SUM(file_size_bytes)) AS total_size
-- FROM file_inventory
-- GROUP BY drive_or_volume, file_extension
-- ORDER BY drive_or_volume, total_bytes DESC;


-- 6. Largest duplicate files (most space to recover).
--
-- SELECT
--     md5_hash,
--     file_size_bytes,
--     pg_size_pretty(file_size_bytes)                      AS size,
--     COUNT(*)                                              AS copies,
--     pg_size_pretty((COUNT(*) - 1) * file_size_bytes)    AS recoverable,
--     ARRAY_AGG(full_path ORDER BY scan_label, full_path) AS paths
-- FROM file_inventory
-- GROUP BY md5_hash, file_size_bytes
-- HAVING COUNT(*) > 1
-- ORDER BY (COUNT(*) - 1) * file_size_bytes DESC
-- LIMIT 50;


-- -----------------------------------------------------------------------
-- MOVE LOG TABLE
-- Records every action taken by move_sortoutall_dups.ps1.
-- This table is append-only — do NOT drop/recreate it between runs.
-- Run create_file_inventory.sql only once; use this block separately
-- if you need to create move_log on an existing database.
-- -----------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS move_log (
    id             BIGSERIAL   PRIMARY KEY,

    -- Run identity (all rows from one script execution share these)
    run_id         TEXT        NOT NULL,   -- YYYYMMDD_HHMMSS of run start
    run_started_at TIMESTAMP   NOT NULL,   -- exact start time of the run
    whatif         BOOLEAN     NOT NULL,   -- true = dry run, no actual move
    db_name        TEXT        NOT NULL,   -- -DbName value used
    log_file       TEXT,                   -- path to the text log for this run

    -- Per-file action
    acted_at       TIMESTAMP   NOT NULL,   -- when this row was written
    outcome        TEXT        NOT NULL,   -- MOVED | WHATIF | MISSING | EXISTS | ERROR
    source_path    TEXT        NOT NULL,   -- original file path
    dest_path      TEXT        NOT NULL,   -- intended destination path
    error_detail   TEXT                    -- populated for ERROR outcome only
);

CREATE INDEX IF NOT EXISTS idx_ml_run_id      ON move_log (run_id);
CREATE INDEX IF NOT EXISTS idx_ml_source_path ON move_log (source_path);
CREATE INDEX IF NOT EXISTS idx_ml_outcome     ON move_log (outcome);
CREATE INDEX IF NOT EXISTS idx_ml_acted_at    ON move_log (acted_at);

-- -----------------------------------------------------------------------
-- USEFUL MOVE_LOG QUERIES
-- -----------------------------------------------------------------------

-- 1. Summary of every run (how many moved, skipped, errors, etc.)
--
-- SELECT
--     run_id,
--     run_started_at,
--     whatif,
--     db_name,
--     COUNT(*)                                         AS total_files,
--     COUNT(*) FILTER (WHERE outcome = 'MOVED')        AS moved,
--     COUNT(*) FILTER (WHERE outcome = 'WHATIF')       AS would_move,
--     COUNT(*) FILTER (WHERE outcome = 'EXISTS')       AS skipped_exists,
--     COUNT(*) FILTER (WHERE outcome = 'MISSING')      AS missing_on_disk,
--     COUNT(*) FILTER (WHERE outcome = 'ERROR')        AS errors
-- FROM move_log
-- GROUP BY run_id, run_started_at, whatif, db_name
-- ORDER BY run_started_at DESC;


-- 2. Every file moved in the most recent run.
--
-- SELECT source_path, dest_path, acted_at
-- FROM move_log
-- WHERE run_id = (SELECT run_id FROM move_log ORDER BY run_started_at DESC LIMIT 1)
--   AND outcome = 'MOVED'
-- ORDER BY source_path;


-- 3. All errors across all runs.
--
-- SELECT run_id, run_started_at, source_path, error_detail
-- FROM move_log
-- WHERE outcome = 'ERROR'
-- ORDER BY run_started_at DESC;


-- 4. Files moved from the originals tree — cross-check against file_inventory
--    to confirm a keeper copy still exists.
--
-- SELECT
--     m.source_path                                  AS moved_file,
--     m.run_id,
--     m.acted_at,
--     fi.full_path                                   AS keeper_copy
-- FROM move_log m
-- JOIN file_inventory fi
--     ON  fi.md5_hash        = (SELECT md5_hash        FROM file_inventory WHERE full_path = m.source_path LIMIT 1)
--     AND fi.file_size_bytes = (SELECT file_size_bytes FROM file_inventory WHERE full_path = m.source_path LIMIT 1)
--     AND fi.full_path      <> m.source_path
-- WHERE m.outcome IN ('MOVED', 'WHATIF')
-- ORDER BY m.source_path;


-- 5. Files that were moved but appear to have NO keeper copy in file_inventory
--    (these may have been moved in error and should be reviewed).
--
-- SELECT m.source_path, m.dest_path, m.run_id, m.acted_at
-- FROM move_log m
-- WHERE m.outcome = 'MOVED'
--   AND NOT EXISTS (
--       SELECT 1
--       FROM file_inventory fi
--       JOIN file_inventory keeper
--           ON  keeper.md5_hash        = fi.md5_hash
--           AND keeper.file_size_bytes = fi.file_size_bytes
--           AND keeper.full_path      <> fi.full_path
--       WHERE fi.full_path = m.source_path
--   )
-- ORDER BY m.source_path;
